#version 430
layout(local_size_x = 16, local_size_y = 16) in;
layout(binding = 0, rgba8) uniform image2D outImg;
uniform sampler2D skybox;
uniform vec3 cam_origin;
uniform vec3 cam_corner;
uniform vec3 cam_hor;
uniform vec3 cam_ver;


void main()
{
	ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
	ivec2 size  = imageSize(outImg);

	if (pixel.x >= size.x || pixel.y >= size.y || size.x == 0 || size.y == 0)
		return;

	vec2 uv = vec2(pixel) / vec2(size);
	vec3 dir = normalize(cam_corner + uv.x * cam_hor + uv.y * cam_ver - cam_origin);
	float lon = atan(dir.z, dir.x);   // atan(y, x) en GLSL = atan2 en C, résultat en [-pi, pi]
	float lat = asin(dir.y);           // [-pi/2, pi/2], Y = axe vertical (cohérent avec ton "up" dans calcul_viewport)
	vec2 sky_uv = vec2(lon / (2.0 * 3.14159265) + 0.5, lat / 3.14159265 + 0.5);
	vec4 color = texture(skybox, sky_uv);



	imageStore(outImg, pixel, color);
}